# Generated by Django 3.2.6 on 2021-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='user_<function uuid4 at 0x7fd9c94a3790>', max_length=100, null=True, unique=True),
        ),
    ]
