# Generated by Django 3.2.6 on 2021-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210824_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='user_5f61f13d-43b9-4935-810a-e75e40fce465', max_length=100, null=True, unique=True),
        ),
    ]
