# Generated by Django 3.2.6 on 2021-08-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210824_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='user_89244cfe-04d8-11ec-8e03-03337f1a2d56', max_length=100, null=True, unique=True),
        ),
    ]
