# Generated by Django 3.2.6 on 2021-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='user_c913e424-2ffc-11ec-8879-311be0840ff2', max_length=20, null=True, unique=True),
        ),
    ]
