# Generated by Django 3.2.6 on 2021-10-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=25, verbose_name='Fiscal Year')),
                ('cash_equiv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cash and Cash Equivalent')),
                ('money_at_call', models.CharField(blank=True, max_length=50, null=True, verbose_name='Money at Call & short notice')),
                ('due_from_nrb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Due From NRB')),
                ('placement_with_bfis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placement with B/FIs')),
                ('loans_advances', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Advances')),
                ('loans_advances_with_bfis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Adavances to B/FIs')),
                ('loans_to_customers', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Advances to Customers')),
                ('investments', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investments')),
                ('invest_security', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment Security')),
                ('invest_in_subsidiaries', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment in Subsidiaries')),
                ('invest_in_associtaes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment in Associates')),
                ('property_investment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment Property')),
                ('other_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Assets')),
                ('derive_fin_instruments', models.CharField(blank=True, max_length=50, null=True, verbose_name='Derivative Financial Instruments')),
                ('trading_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Trading Assets')),
                ('current_tax_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Tax Assets')),
                ('deferred_tax_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Deferred Tax Assets')),
                ('goodwill_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Goodwill and Intangible Assets')),
                ('property_equipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Property & Equipment')),
                ('total_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Assets')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company')),
            ],
        ),
    ]
