# Generated by Django 3.2.6 on 2021-10-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Fiscal Year')),
                ('borrowings', models.CharField(blank=True, max_length=25, null=True, verbose_name='Borrowings')),
                ('due_to_fbis', models.CharField(blank=True, max_length=25, null=True, verbose_name='Due to B/FIs')),
                ('due_to_nrb', models.CharField(blank=True, max_length=25, null=True, verbose_name='Due to NRB')),
                ('borrowing', models.CharField(blank=True, max_length=25, null=True, verbose_name='Borrowing')),
                ('debt_securities', models.CharField(blank=True, max_length=25, null=True, verbose_name='Debt Securities')),
                ('deposits', models.CharField(blank=True, max_length=25, null=True, verbose_name='Deposits')),
                ('other_liabilities', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other Liabilities')),
                ('derive_fin_instruments', models.CharField(blank=True, max_length=25, null=True, verbose_name='Derivative financial instruments')),
                ('provisions', models.CharField(blank=True, max_length=25, null=True, verbose_name='Provisions')),
                ('current_tax_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Current tax liabilities')),
                ('deferred_tax_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Deferred tax liabilities')),
                ('subordinated_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Subordinated liabilities')),
                ('other_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other liabilities')),
                ('total_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total liabilities')),
                ('share_holder_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Share holders equity')),
                ('paidup_capital', models.CharField(blank=True, max_length=25, null=True, verbose_name='Paid up capital')),
                ('reserves_surpluses', models.CharField(blank=True, max_length=25, null=True, verbose_name='Reserves & Surpluses')),
                ('shre_premium', models.CharField(blank=True, max_length=25, null=True, verbose_name='Share Premium')),
                ('retain_earnings', models.CharField(blank=True, max_length=25, null=True, verbose_name='Retained Earnings')),
                ('reserves', models.CharField(blank=True, max_length=25, null=True, verbose_name='Reserves')),
                ('non_controll_interest', models.CharField(blank=True, max_length=25, null=True, verbose_name='Non Controlling Interest')),
                ('total_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total Equity')),
                ('total_liab_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total liabilities & Equity')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Fiscal Year')),
                ('int_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest Income')),
                ('int_expense', models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest Expense')),
                ('net_int_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Net Interest Income')),
                ('fees_comission_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Fees & Commission Income')),
                ('fees_commissoin_exp', models.CharField(blank=True, max_length=25, null=True, verbose_name='Fees & Commission Expenses')),
                ('net_fees_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Net fees & commission income')),
                ('net_fees_interest_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Net interest, fees & commission income')),
                ('net_trading_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Net Trading Income')),
                ('other_operating_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other operating income')),
                ('impairment_charge', models.CharField(blank=True, max_length=25, null=True, verbose_name='Impairment Charge')),
                ('net_operating_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Net operating income')),
                ('personnel_expenses', models.CharField(blank=True, max_length=25, null=True, verbose_name='Personnel Expenses')),
                ('other_operating_exp', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other operating expenses')),
                ('depreciation', models.CharField(blank=True, max_length=25, null=True, verbose_name='Depreciation & Amortization')),
                ('operating_profit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Operating profit')),
                ('non_operating_income', models.CharField(blank=True, max_length=25, null=True, verbose_name='Non operating income')),
                ('non_operating_expense', models.CharField(blank=True, max_length=25, null=True, verbose_name='Non-operaing expenses')),
                ('non_operating_pl_ratio', models.CharField(blank=True, max_length=25, null=True, verbose_name='Non-operating income/(expenses)')),
                ('profit_bef_tax', models.CharField(blank=True, max_length=25, null=True, verbose_name='Profit before tax')),
                ('income_tax', models.CharField(blank=True, max_length=25, null=True, verbose_name='Income tax')),
                ('current_tax', models.CharField(blank=True, max_length=25, null=True, verbose_name='Current tax')),
                ('deferred_tax', models.CharField(blank=True, max_length=25, null=True, verbose_name='Deferred tax')),
                ('ratio_profit_loss', models.CharField(blank=True, max_length=25, null=True, verbose_name='Profit/Loss for the period')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company')),
            ],
        ),
    ]
