# Generated by Django 3.2.6 on 2021-10-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_fees_commissoin_exp_incomestatement_fees_commission_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='listed_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='market_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
