# Generated by Django 3.2.6 on 2021-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20211019_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Development Bank', 'Development Bank'), ('Commercial Bank', 'Commercial Bank'), ('Microfinance', 'Microfinance'), ('Hydropower', 'Hydropower'), ('Hotels', 'Hotels'), ('Life Insurance', 'Life Insurance')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
