# Generated by Django 3.2.6 on 2021-11-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20211020_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=25, verbose_name='Fiscal Year')),
                ('cash_equiv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cash and Cash Equivalent')),
                ('money_at_call', models.CharField(blank=True, max_length=50, null=True, verbose_name='Money at Call & short notice')),
                ('due_from_nrb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Due From NRB')),
                ('placement_with_bfis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placement with B/FIs')),
                ('loans_advances', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Advances')),
                ('loans_advances_with_bfis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Adavances to B/FIs')),
                ('loans_to_customers', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loans & Advances to Customers')),
                ('investments', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investments')),
                ('invest_security', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment Security')),
                ('invest_in_subsidiaries', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment in Subsidiaries')),
                ('invest_in_associtaes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment in Associates')),
                ('property_investment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Investment Property')),
                ('other_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Assets')),
                ('trading_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Trading Assets')),
                ('current_tax_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Tax Assets')),
                ('deferred_tax_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Deferred Tax Assets')),
                ('goodwill_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Goodwill and Intangible Assets')),
                ('property_equipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Property & Equipment')),
                ('total_assets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Assets')),
                ('borrowings', models.CharField(blank=True, max_length=25, null=True, verbose_name='Borrowings')),
                ('due_to_fbis', models.CharField(blank=True, max_length=25, null=True, verbose_name='Due to B/FIs')),
                ('due_to_nrb', models.CharField(blank=True, max_length=25, null=True, verbose_name='Due to NRB')),
                ('borrowing', models.CharField(blank=True, max_length=25, null=True, verbose_name='Borrowing')),
                ('debt_securities', models.CharField(blank=True, max_length=25, null=True, verbose_name='Debt Securities')),
                ('deposits', models.CharField(blank=True, max_length=25, null=True, verbose_name='Deposits')),
                ('other_liabilities', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other Liabilities')),
                ('derive_fin_instruments', models.CharField(blank=True, max_length=25, null=True, verbose_name='Derivative financial instruments')),
                ('provisions', models.CharField(blank=True, max_length=25, null=True, verbose_name='Provisions')),
                ('current_tax_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Current tax liabilities')),
                ('deferred_tax_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Deferred tax liabilities')),
                ('subordinated_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Subordinated liabilities')),
                ('other_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Other liabilities')),
                ('total_liab', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total liabilities')),
                ('share_holder_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Share holders equity')),
                ('paidup_capital', models.CharField(blank=True, max_length=25, null=True, verbose_name='Paid up capital')),
                ('reserves_surpluses', models.CharField(blank=True, max_length=25, null=True, verbose_name='Reserves & Surpluses')),
                ('shre_premium', models.CharField(blank=True, max_length=25, null=True, verbose_name='Share Premium')),
                ('retain_earnings', models.CharField(blank=True, max_length=25, null=True, verbose_name='Retained Earnings')),
                ('reserves', models.CharField(blank=True, max_length=25, null=True, verbose_name='Reserves')),
                ('non_controll_interest', models.CharField(blank=True, max_length=25, null=True, verbose_name='Non Controlling Interest')),
                ('total_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total Equity')),
                ('total_liab_equity', models.CharField(blank=True, max_length=25, null=True, verbose_name='Total liabilities & Equity')),
            ],
        ),
        migrations.RemoveField(
            model_name='liability',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Liability',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company'),
        ),
    ]
